<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />
	
  <PropertyGroup>
	  <AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
	  <RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
	  <Title>Kafka Connector for MQContract</Title>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.*" />
    <PackageReference Include="Confluent.SchemaRegistry" Version="2.*" />
    <PackageReference Include="JsonSchema.Net" Version="7.*" />
    <PackageReference Include="JsonSchema.Net.Generation" Version="5.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
  </ItemGroup>
</Project>
