<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Shared.props" />
	
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>MQContract</RootNamespace>
	<Title>Abstractions for MQContract</Title>
  </PropertyGroup>

</Project>
