<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />

	<PropertyGroup>
		<AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
		<Title>RabbitMQ Connector for MQContract</Title>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Connection.cs~RF31a2302.TMP" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Include="..\Shared\BatchedMessageStream.cs" Link="BatchedMessageStream.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="RabbitMQ.Client" Version="7.*" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
</Project>
