<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
		<Title>In Memory Connector for MQContract</Title>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\..\Core\EnumerableExtensions.cs" Link="EnumerableExtensions.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Vsxmd" Version="1.4.6" />
	</ItemGroup>

</Project>
