<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />

	<PropertyGroup>
		<AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
		<Title>In Memory Connector for MQContract</Title>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\..\Core\EnumerableExtensions.cs" Link="EnumerableExtensions.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
	</ItemGroup>

</Project>
