using MQContract.Attributes;

namespace MQContract.Defaults
{
    [UseMqContract(typeof(byte[]), typeof(ByteArrayEncoder), [])]
    [UseMqContract(typeof(byte), typeof(ByteEncoder), [])]
    [UseMqContract(typeof(bool), typeof(BooleanEncoder), [])]
    [UseMqContract(typeof(bool[]), typeof(BooleanEncoder), [])]
    [UseMqContract(typeof(IEnumerable<bool>), typeof(BooleanEncoder), [])]
    [UseMqContract(typeof(char), typeof(CharEncoder), [])]
    [UseMqContract(typeof(decimal), typeof(DecimalEncoder), [])]
    [UseMqContract(typeof(decimal[]), typeof(DecimalEncoder), [])]
    [UseMqContract(typeof(IEnumerable<decimal>), typeof(DecimalEncoder), [])]
    [UseMqContract(typeof(double), typeof(DoubleEncoder), [])]
    [UseMqContract(typeof(double[]), typeof(DoubleEncoder), [])]
    [UseMqContract(typeof(IEnumerable<double>), typeof(DoubleEncoder), [])]
    [UseMqContract(typeof(float), typeof(FloatEncoder), [])]
    [UseMqContract(typeof(float[]), typeof(FloatEncoder), [])]
    [UseMqContract(typeof(IEnumerable<float>), typeof(FloatEncoder), [])]
    [UseMqContract(typeof(Half), typeof(HalfEncoder), [])]
    [UseMqContract(typeof(Half[]), typeof(HalfEncoder), [])]
    [UseMqContract(typeof(IEnumerable<Half>), typeof(HalfEncoder), [])]
    [UseMqContract(typeof(int), typeof(IntEncoder), [])]
    [UseMqContract(typeof(int[]), typeof(IntEncoder), [])]
    [UseMqContract(typeof(IEnumerable<int>), typeof(IntEncoder), [])]
    [UseMqContract(typeof(long), typeof(LongEncoder), [])]
    [UseMqContract(typeof(long[]), typeof(LongEncoder), [])]
    [UseMqContract(typeof(IEnumerable<long>), typeof(LongEncoder), [])]
    [UseMqContract(typeof(short), typeof(ShortEncoder), [])]
    [UseMqContract(typeof(short[]), typeof(ShortEncoder), [])]
    [UseMqContract(typeof(IEnumerable<short>), typeof(ShortEncoder), [])]
    [UseMqContract(typeof(string), typeof(StringEncoder), [])]
    [UseMqContract(typeof(uint), typeof(UIntEncoder), [])]
    [UseMqContract(typeof(uint[]), typeof(UIntEncoder), [])]
    [UseMqContract(typeof(IEnumerable<uint>), typeof(UIntEncoder), [])]
    [UseMqContract(typeof(ulong), typeof(ULongEncoder), [])]
    [UseMqContract(typeof(ulong[]), typeof(ULongEncoder), [])]
    [UseMqContract(typeof(IEnumerable<ulong>), typeof(ULongEncoder), [])]
    [UseMqContract(typeof(ushort), typeof(UShortEncoder), [])]
    [UseMqContract(typeof(ushort[]), typeof(UShortEncoder), [])]
    [UseMqContract(typeof(IEnumerable<ushort>), typeof(UShortEncoder), [])]
    internal partial class DefaultMessageContext : MQContractMessageContext
    {
    }
}
