<Project>
	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Company>$(AssemblyName)</Company>
		<VersionPrefix>4.0.0</VersionPrefix>
		<PackageProjectUrl>https://github.com/roger-castaldo/MQContract</PackageProjectUrl>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/roger-castaldo/MQContract</RepositoryUrl>
		<AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
		<FileVersion>$(VersionPrefix)</FileVersion>
		<PackageTags>Message Queue MQ Contract ServiceBus Messaging Abstraction PubSub QueryResponse</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<IncludeSymbols>True</IncludeSymbols>
		<RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationMarkdown>$(MSBuildProjectDirectory)\Readme.md</DocumentationMarkdown>
		<Authors>roger-castaldo</Authors>
		<Company>$(AssemblyName)</Company>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Vsxmd" Version="1.4.6" Condition="'$(BlockMD)' != 'true'">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<PropertyGroup>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
      </PropertyGroup>

      <ItemGroup>
        <None Include="Readme.md" Pack="true" PackagePath="\" />
      </ItemGroup>
</Project>