<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />
	
  <PropertyGroup>
	  <AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
	  <RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
	  <Title>NATS.io Connector for MQContract</Title>
  </PropertyGroup>
	
  <ItemGroup>
    <Compile Include="..\Shared\BatchedMessageStream.cs" Link="BatchedMessageStream.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NATS.Net" Version="2.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
  </ItemGroup>
</Project>
