<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />

	<PropertyGroup>
		<AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
		<Title>Redis Connector for MQContract</Title>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\Shared\BatchedMessageStream.cs" Link="BatchedMessageStream.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="StackExchange.Redis" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
</Project>
