<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />
	<PropertyGroup>
		<AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
		<Title>AzureServiceBus Connector for MQContract</Title>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\Shared\BaseLoopSubscription.cs" Link="BaseLoopSubscription.cs" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.*" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
  </ItemGroup>

</Project>
