<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Shared.props" />

	<PropertyGroup>
		<AssemblyName>MQContract.CQRS</AssemblyName>
		<RootNamespace>MQContract.CQRS</RootNamespace>
		<Title>CQRS wrapper for MQContract</Title>
	</PropertyGroup>
	
	<ItemGroup>
      <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    </ItemGroup>
	

</Project>
