<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<IsRoslynAnalyzer>true</IsRoslynAnalyzer>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<AssemblyName>MQContract.Generators</AssemblyName>
		<RootNamespace>MQContract.Generators</RootNamespace>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
		<RestoreAdditionalProjectSources></RestoreAdditionalProjectSources>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" PrivateAssets="all"/>
	</ItemGroup>

</Project>