<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />
	
  <PropertyGroup>
	  <AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
	  <RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
	  <Title>KubeMQ Connector for MQContract</Title>
  </PropertyGroup>
	
  <ItemGroup>
    <Compile Include="..\Shared\BatchedMessageStream.cs" Link="BatchedMessageStream.cs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Google.Protobuf" Version="3.*" />
	  <PackageReference Include="Grpc.Net.Client" Version="2.*" />
	  <PackageReference Include="Grpc.Tools" Version="2.*">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
  </ItemGroup>
</Project>
