<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />
	<PropertyGroup>
		<AssemblyName>MQContract.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>MQContract.$(MSBuildProjectName)</RootNamespace>
		<Title>Amazon SNS/SQS Connector for MQContract</Title>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.*" />
	  <PackageReference Include="AWSSDK.SQS" Version="4.*" />
	</ItemGroup>
</Project>
