name: .NET-Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Restore
      run: dotnet restore MQContract.sln --force
    - name: Build-8.0 tesitng core
      run: dotnet build -p:BlockMD=true --no-restore Testing/Core
    - name: Build-8.0 tesitng cqrs
      run: dotnet build -p:BlockMD=true --no-restore Testing/CQRSTesting
    - name: Build-8.0 tesitng codegen
      run: dotnet build -p:BlockMD=true --no-restore Testing/CodeGenTesting
    - name: Test-8.0 core
      run: dotnet test -p:BlockMD=true --no-build --verbosity normal Testing/Core
    - name: Test-8.0 cqrs
      run: dotnet test -p:BlockMD=true --no-build --verbosity normal Testing/CQRSTesting
    - name: Test-8.0 codegen
      run: dotnet test -p:BlockMD=true --no-build --verbosity normal Testing/CodeGenTesting
