name: "Dot Net Test Reporter"

on:
  pull_request_target:
    types: [ opened, synchronize ]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Restore dependencies
      run: dotnet restore -p:BlockMD=true Testing/Core
    - name: Build-8.0
      run: dotnet build -p:BlockMD=true --no-restore Testing/Core
    - name: Test-8.0
      run: dotnet test -p:BlockMD=true --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"Code Coverage" Testing/Core
    - name: report results
      uses: bibipkins/dotnet-test-reporter@v1.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Unit Test Results'
        results-path: ./**/*.trx
        coverage-path: ./**/*.coverage
        coverage-threshold: 90
