name: .NET-Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Restore
      run: dotnet restore MQContract.sln --force
    - name: Build testing core
      run: dotnet build -p:BlockMD=true --no-restore Testing/Core
    - name: Build testing cqrs
      run: dotnet build -p:BlockMD=true --no-restore Testing/CQRSTesting
    - name: Build testing codegen
      run: dotnet build -p:BlockMD=true --no-restore Testing/CodeGenTesting
    - name: Build testing activemq
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/ActiveMQ
    - name: Build testing amazonsqns
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/AmazonSQNS
    - name: Build testing azureservicebus
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/AzureServiceBus
    - name: Build testing googlepubsub
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/GooglePubSub
    - name: Build testing hivemq
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/HiveMQ
    - name: Build testing inmemory
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/InMemory
    - name: Build testing kafka
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/Kafka
    - name: Build testing nats
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/Nats
    - name: Build testing pulsar
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/Pulsar
    - name: Build testing rabbitmq
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/RabbitMQ
    - name: Build testing redis
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/Redis
    - name: Build testing zeromq
      run: dotnet build -p:BlockMD=true --no-restore Testing/ConnectorTesting/ZeroMQ
    - name: Test core
      run: dotnet test -p:BlockMD=true --no-build --verbosity normal Testing/Core
    - name: Test cqrs
      run: dotnet test -p:BlockMD=true --no-build --verbosity normal Testing/CQRSTesting
    - name: Test codegen
      run: dotnet test -p:BlockMD=true --no-build --verbosity normal Testing/CodeGenTesting
    - name: Test activemq
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/ActiveMQ
    - name: Test amazonsqns
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/AmazonSQNS
    - name: Test azureservicebus
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/AzureServiceBus
    - name: Test googlepubsub
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/GooglePubSub
    - name: Test hivemq
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/HiveMQ
    - name: Test inmemory
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/InMemory
    - name: Test kafka
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/Kafka
    - name: Test nats
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/Nats
    - name: Test pulsar
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/Pulsar
    - name: Test rabbitmq
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/RabbitMQ
    - name: Test redis
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/Redis
    - name: Test zeromq
      run: dotnet test -p:BlockMD=true --no-build Testing/ConnectorTesting/ZeroMQ
